config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'calendars#index'

  resources :calendars do
    resources :events
  end

  post 'search' => 'users#search'

  get 'accept' => 'invites#accept'
  get 'decline' => 'invites#decline'

end

app/models/calendar.rb
class Calendar < ActiveRecord::Base

    has_many :users_calendars
    has_many :users, :through => :users_calendars
    has_many :events, :dependent => :destroy

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :calendar
end

app/models/invite.rb
class Invite < ActiveRecord::Base
  belongs_to :calendar
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable

  has_many :users_calendars
  has_many :calendars, :through => :users_calendars
    

end

app/models/users_calendar.rb
class UsersCalendar < ActiveRecord::Base
  belongs_to :user
  belongs_to :calendar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name
    devise_parameter_sanitizer.for(:sign_up) << :last_name
  end
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController

  before_filter :authenticate_user!

  def index
    @calendars = Calendar.where()
    user_calendars = UsersCalendar.where(user_id:current_user.id).pluck(:calendar_id)
    @calendars = Calendar.where(id:user_calendars)

    @invites = Invite.where(recipient:current_user.id)
  end

  def new
    @calendar = Calendar.new
  end

  def create
    binding.pry
    @calendar = Calendar.new(calendar_params)
    @calendar.save
    user_calendar = UsersCalendar.new()
    user_calendar.user = current_user
    user_calendar.calendar = @calendar
    user_calendar.save
    redirect_to new_calendar_event_path(@calendar)
  end

  def show
    @calendar = Calendar.find(params[:id])
  end


  private

  def calendar_params
    params.require(:calendar).permit(:name, :color)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_filter :authenticate_user!

  def index

    @events = Events.all
  end

  def new
    # binding.pry
    @calendar = Calendar.find(params[:calendar_id])
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.save
    @calendar = Calendar.find(params[:calendar_id])
    redirect_to calendar_path(@calendar)
  end

  def edit
    @event = Event.find(params[:id])
    @calendar = Calendar.find(params[:calendar_id])
  end

  def update
    @event = Event.find(params[:id])
    @calendar = Calendar.find(params[:calendar_id])
    @event.update(event_params)
    if @event.save
      redirect_to calendar_path(@calendar)
    else
      render :edit
    end

  end


  private

  def event_params
    params.require(:event).permit(:start_date, :end_date, :start_time, :end_time, :description, :calendar_id)
  end

end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController

  def accept
    @calendar = Calendar.find(params[:calendar_id])
    user_calendar = UsersCalendar.new()
    user_calendar.user = current_user
    user_calendar.calendar = @calendar
    user_calendar.save
    invite = Invite.find_by(calendar_id:@calendar.id, recipient:current_user.id)
    invite.destroy
    redirect_to calendars_path
  end


  def decline
    @calendar = Calendar.find(params[:calendar_id])
    invite = Invite.find_by(calendar_id:@calendar.id, recipient:current_user.id)
    invite.destroy
    redirect_to calendars_path
  end

end

app/controllers/users_calendar_controller.rb
class UsersCalendarController < ApplicationController

  def index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def search
    # binding.pry
    calendar = Calendar.find(params[:calendar_id])
    recipient = User.find_by(email:params[:email])
    if recipient && calendar
      invite = Invite.create(user_id:current_user.id, recipient:recipient.id, calendar_id:calendar.id, status:"open")
      recipient.open_invite = true
      recipient.save
    end
    redirect_to calendar_path(calendar)
  end



end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def welcome

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/calendars/_form.html.erb
<%= form_for(@calendar) do |f| %>
  <% if @calendar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@calendar.errors.count, "error") %> prohibited this calendar from being saved:</h2>

      <ul>
      <% @calendar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.color_field :color %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/calendars/index.html.erb
<div class="container">
  <div class="wrapper">

    <div class="row">
      <div class="col-xs-2">
        <%= link_to "Add Calendar", new_calendar_path() %>
      </div>
      <div class="col-xs-2">
        <%= link_to "Sign out", destroy_user_session_path, method: :delete  %>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12">
        <h2>Your Calendars</h2>

        <div class="calendar_list">
          <% @calendars.each do |calendar| %>
          <div class="row">
            <div class="col-xs-12">
              <span style="background-color:<%= calendar.color %>" class="circle circle_icon"></span>
              <%= link_to calendar.name, calendar_path(calendar) %>
            </div>
          </div>
          <% end %>
        </div>

      </div>
    </div>

    <% if @invites.count > 0 %>
      <div class="row">
        <div class="col-xs-12">
          <h2>Your Open Invites</h2>

          <div class="calendar_list">
            <% @invites.each do |invite| %>
            <div class="row">
              <div class="col-xs-12">
                Invite from: <%= User.find(invite.user_id).email %><br>
                Calendar: <%= Calendar.find(invite.calendar.id).name %><br>
                <%= link_to "Accept", accept_path(calendar_id:Calendar.find(invite.calendar.id)) %> / <%= link_to "Decline", decline_path(calendar_id:Calendar.find(invite.calendar.id)) %>
              </div>
            </div>
            <% end %>
          </div>

        </div>
      </div>
    <% end %>


  </div>
</div>

app/views/calendars/new.html.erb
<div class="container">
  <div class="wrapper">

    <h1>New Calendar</h1>

    <%= render 'form' %>

    <%= link_to 'Back', :back %>

  </div>
</div>

app/views/calendars/show.html.erb
<div class="container">
  <div class="menu">
    <div class="row">
      <div class="col-xs-2">
        <%= link_to "Home", root_path %>
      </div>
      <div class="col-xs-2">
        <%= link_to "Edit Calendar", edit_calendar_path(@calendar) %>
      </div>
      <div class="col-xs-2">
        <%= link_to "Share Calendar", search_path(), "data-toggle" => "modal", "data-target" => "#myModal" %>
      </div>

      <div class="col-xs-2">
        Delete Calendar
      </div>
      <div class="col-xs-2">
        <%= link_to "Sign out", destroy_user_session_path, method: :delete  %>
      </div>
    </div>
  </div>
</div>

<div class="calendar_heading" style="background-color:<%= @calendar.color%>">
  <div class="row">
    <div class="col-xs-4">
      <h3><%= Time.now().strftime("%B") %></h3>
    </div>
    <div class="col-xs-4 text-center calendar_name">
      <h3><%= @calendar.name %> Calendar</h3>
    </div>
    <div class="col-xs-4 text-right">
      <%= link_to new_calendar_event_path(@calendar) do%>
      <h3><i class="fa fa-plus-circle"></i> Add Event</h3>
      <% end %>
    </div>
  </div>
</div><!-- calendar_heading -->

<div class="calendar_body">

  <% @calendar.events.order(start_date: :asc, start_time: :asc).each do |event| %>
  <div class="row">
    <div class="col-xs-12">
      <h2><%= event.start_date.strftime("%A %b %d, %Y") %></h2>
      <hr>
    </div>
  </div><!-- row -->

  <div class="row event_detail">
    <div class="event_time">
      <%= event.start_time.strftime("%I:%M %p") %>
    </div>
    <div class="event_descrip">
      <div class="row">
        <div class="col-xs-12">
          <%= event.description %>
          <%= link_to edit_calendar_event_path(@calendar, event) do %>
          <i class="fa fa-pencil"></i>
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12">
          Attending:
        </div>
      </div>
    </div>
  </div><!-- row -->


  <% end %>
</div><!-- calendar_body -->


<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Send invite to user</h4>
      </div>

      <div class="modal-body">
        <%= form_tag search_path, method: :post, class:"form-horizontal" do%>
          <div class="box-body">

            <div class="row">
                <div class="col-xs-12" id="last_name_div">
                  <%= hidden_field_tag "calendar_id", "#{@calendar.id}" %>
                  <%= text_field_tag "email", nil, placeholder: 'User email...' %>
                </div>
            </div><!-- /.row -->

          </div><!-- /.box-body -->
        </div><!-- /.modal-body -->

        <div class="modal-footer">
          <%= submit_tag 'Submit', class:"btn btn-info pull-right" %>
        </div>
      <% end %>

    </div><!-- End Modal Content  -->
  </div><!-- End Modal Dialog -->
</div> <!-- End Modal  -->

app/views/events/_form.html.erb
<%= form_for [@calendar, @event] do |f| %>
<% if @event.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

  <ul>
    <% @event.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<%= f.hidden_field :calendar_id, value: @calendar.id %>

<div class="field">
  <%= f.label :date %><br>
  <%= f.text_field :start_date, class:"datepicker", placeholder:"Date" %>
</div>
<div class="field">
  <%= f.label :time %><br>
  <%= f.time_field :start_time, placeholder:"Time" %>
</div>
<div class="field">
  <%= f.label :event %><br>
  <%= f.text_field :description, placeholder:"Event" %>
</div>

<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/events/edit.html.erb
<div class="container">
  <div class="wrapper">

    <h1>Edit Calendar Event</h1>

    <%= render 'form' %>

    <%= link_to 'Back', :back %>

  </div>
</div>

app/views/events/new.html.erb
<div class="container">
  <div class="wrapper">

    <h1>New Calendar Event</h1>

    <%= render 'form' %>

    <%= link_to 'Back', :back %>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LOML-Calendar</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

  <!-- Latest compiled and minified Fontawesome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

  <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>

  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">

</head>
<body>

  <!-- <p class="notice"><%#= notice %></p>
  <p class="alert"><%#= alert %></p> -->

  <%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<div class="container">
  <div class="wrapper">
    <div class="row">
      
      <div class="col-xs-12 text-center">

        <%= link_to new_user_session_path do %>
        <div class="circle circle_small">
          <div>
            <i class="fa fa-sign-in"></i> Sign in
          </div>
        </div>
        <% end %>

        <%= link_to new_user_registration_path do %>
        <div class="circle circle_small">
          <div>
            <i class="fa fa-plus-circle"></i> Sign up
          </div>
        </div>
        <% end %>
      </div>

    </div>
  </div>
</div>